import { Metadata } from "next";
import { FC } from "react";

import { ButtonGoBack, Container } from "@/src/shared/ui";
import { DashboardUserLogList } from "@/src/widgets/DashboardUserLogList";

export const metadata: Metadata = {
  title: "Lib Space | Панель управления | Логи",
  description: "Generated by create next app",
};

const DashboardUserLogPage: FC = () => {
  return (
    <Container>
      <div className="flex items-center gap-2 mb-4">
        <ButtonGoBack />
        <h2 className="text-3xl font-semibold">Логи</h2>
      </div>
      <DashboardUserLogList />
    </Container>
  );
};

export default DashboardUserLogPage;
