import type { Metadata } from "next";

import { Header } from "@/src/widgets/Header";

export const metadata: Metadata = {
  title: "Lib Space | Книга",
  description: "Generated by create next app",
};

export default function BookLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header
        className="mb-2"
        hasFilters={false}
        hasSearch={false}
        hasGrid={false}
        hasGoBack
      />
      <main className="flex-1 flex">{children}</main>
    </>
  );
}
