import { Metadata } from "next";
import { FC } from "react";
import { PlusCircle } from "lucide-react";

import { Container, DashboardDrawer } from "@/src/shared/ui";
import { DashboardUsersList } from "@/src/widgets/DashboardUsersList";
import { Button } from "@/src/shared/shadcn";
import { CreateUser } from "@/src/features/CreateUser";

export const metadata: Metadata = {
  title: "Lib Space | Панель управления | Пользователи",
  description: "Generated by create next app",
};

const DashboardUsersPage: FC = () => {
  return (
    <Container>
      <div className="flex justify-between items-center gap-2 mb-4">
        <h2 className="text-3xl font-semibold">Пользователи</h2>
        <DashboardDrawer title="Создание пользователя" content={<CreateUser />}>
          <Button>
            <PlusCircle />
            <div>Создать пользователя</div>
          </Button>
        </DashboardDrawer>
      </div>
      <DashboardUsersList />
    </Container>
  );
};

export default DashboardUsersPage;
