import { Metadata } from "next";
import { FC } from "react";

import { Container } from "@/src/shared/ui";

export const metadata: Metadata = {
  title: "Lib Space | Панель управления | Пользователи",
  description: "Generated by create next app",
};

const DashboardUsersPage: FC = () => {
  return (
    <Container>
      <h2 className="text-3xl font-semibold mb-2">Пользователи</h2>
    </Container>
  );
};

export default DashboardUsersPage;
