import { Metadata } from "next";
import { FC } from "react";
import { PlusCircle } from "lucide-react";

import { Container } from "@/src/shared/ui";
import { DashboardUsersList } from "@/src/widgets/DashboardUsersList";
import { Button } from "@/src/shared/shadcn";
import { CreationUserDrawer } from "@/src/widgets/CreationUserDrawer";

export const metadata: Metadata = {
  title: "Lib Space | Панель управления | Пользователи",
  description: "Generated by create next app",
};

const DashboardUsersPage: FC = () => {
  return (
    <Container>
      <h2 className="text-3xl font-semibold mb-3">Пользователи</h2>
      <CreationUserDrawer>
        <Button className="mb-3">
          <PlusCircle />
          <div>Создать пользователя</div>
        </Button>
      </CreationUserDrawer>
      <DashboardUsersList />
    </Container>
  );
};

export default DashboardUsersPage;
