import { Metadata } from "next";
import { FC } from "react";
import { PlusCircle } from "lucide-react";

import { Container, DashboardDrawer } from "@/src/shared/ui";
import { Button } from "@/src/shared/shadcn";
import { DashboardGenresList } from "@/src/widgets/DashboardGenresList";
import { CreateGenre } from "@/src/features/CreateGenre";

export const metadata: Metadata = {
  title: "Lib Space | Панель управления | Жанры",
  description: "Generated by create next app",
};

const DashboardGenresPage: FC = () => {
  return (
    <Container>
      <div className="flex justify-between items-center gap-2 mb-4">
        <h2 className="text-3xl font-semibold">Жанры</h2>
        <DashboardDrawer
          title="Добавление нового жанра"
          content={<CreateGenre />}
        >
          <Button>
            <PlusCircle />
            <div>Добавить жанр</div>
          </Button>
        </DashboardDrawer>
      </div>
      <DashboardGenresList />
    </Container>
  );
};

export default DashboardGenresPage;
