import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";

import { Header } from "@/src/widgets/Header";
import { SidebarProvider, SidebarTrigger } from "@/src/shared/shadcn";
import { DashBoardSidebar } from "@/src/widgets/DashBoardSidebar";
import { MENU_LIST } from "@/src/shared/constant";

export const metadata: Metadata = {
  title: "Lib Space | Панель управления",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = (await cookieStore).get("access_token")?.value;

  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/me`, {
    headers: {
      cookie: `access_token=${token}`,
    },
    cache: "no-store",
  });

  if (res.status === 401) {
    console.log(res.status);
    console.log(await res.json());
    console.log("redirect to login");
    console.log(token);
    redirect(MENU_LIST.login);
  }

  const user = await res.json();

  return (
    <SidebarProvider>
      <DashBoardSidebar user={user} />
      <div className="flex flex-col w-full">
        <Header
          className="mb-2"
          hasFilters={false}
          hasGrid={false}
          hasSearch={false}
          sidebarTrigger={<SidebarTrigger />}
        />
        <main className="flex-1 flex">{children}</main>
      </div>
    </SidebarProvider>
  );
}
