import { FC } from "react";
import { Metadata } from "next";
import { redirect } from "next/navigation";

import { Container } from "@/src/shared/ui";
import { ProfileContent } from "@/src/widgets/ProfileContent";
import { authCheck } from "@/src/shared/utils/authCheck";
import { MENU_LIST } from "@/src/shared/constant";

export const metadata: Metadata = {
  title: "Lib Space | Профиль",
  description: "Generated by create next app",
};

const ProfilePage: FC = async () => {
  const { isAuthenticated } = await authCheck();

  if (!isAuthenticated) {
    redirect(MENU_LIST.login);
  }

  return (
    <Container className="mb-2">
      <ProfileContent />
    </Container>
  );
};

export default ProfilePage;
