import { FC } from "react";
import { Metadata } from "next";

import { Container } from "@/src/shared/ui";
import { ProfileContent } from "@/src/widgets/ProfileContent";

export const metadata: Metadata = {
  title: "Lib Space | Профиль",
  description: "Generated by create next app",
};

const ProfilePage: FC = () => {
  return (
    <Container>
      <ProfileContent />
    </Container>
  );
};

export default ProfilePage;
