import { Metadata } from "next";
import { FC } from "react";
import { PlusCircle } from "lucide-react";

import { Container, DashboardDrawer } from "@/src/shared/ui";
import { DashboardBooksList } from "@/src/widgets/DashboardBooksList";
import { Button } from "@/src/shared/shadcn";
import { CreateBook } from "@/src/features/CreateBook";

export const metadata: Metadata = {
  title: "Lib Space | Панель управления | Книги",
  description: "Generated by create next app",
};

const DashboardBooksPage: FC = () => {
  return (
    <Container>
      <div className="flex justify-between items-center gap-2 mb-4">
        <h2 className="text-3xl font-semibold">Книги</h2>
        <DashboardDrawer title="Создание книгу" content={<CreateBook />}>
          <Button>
            <PlusCircle />
            <div>Создать книгу</div>
          </Button>
        </DashboardDrawer>
      </div>
      <DashboardBooksList />
    </Container>
  );
};

export default DashboardBooksPage;
