import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SpaceLib",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
