import { redirect } from "next/navigation";
import { FC } from "react";
import { Metadata } from "next";

import { MENU_LIST } from "@/src/shared/constant";
import { Container } from "@/src/shared/ui";
import { authCheck } from "@/src/shared/utils";
import { UserBorrowingsList } from "@/src/widgets/UserBorrowingsList";

export const metadata: Metadata = {
  title: "Lib Space | Мои аренды книг",
  description: "Generated by create next app",
};

const BorrowingsPage: FC = async () => {
  const { user } = await authCheck();

  if (!user) {
    redirect(MENU_LIST.login);
  }

  return (
    <div className="w-full">
      <Container>
        <h2 className="text-3xl font-semibold mb-3">Мои аренды книг</h2>
        <UserBorrowingsList user={user} />
      </Container>
    </div>
  );
};

export default BorrowingsPage;
