import type { Metadata } from "next";

import { Header } from "@/src/widgets/Header";
import { Menu } from "@/src/widgets/Menu";

export const metadata: Metadata = {
  title: "SpaceLib",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header className="mb-2" />
      <main>{children}</main>
      <Menu />
    </>
  );
}
