import type { Metadata } from "next";
import { Suspense } from "react";

import { Header } from "@/src/widgets/Header";
import { Menu } from "@/src/widgets/Menu";

export const metadata: Metadata = {
  title: "Lib Space | Каталог книг",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Suspense>
        <Header className="mb-2" />
      </Suspense>
      <main className="flex-1 flex">{children}</main>
      <Menu />
    </>
  );
}
